In [1]:
import numpy as np

In [2]:
a=np.arange(4)

In [7]:
print("a   =",a)
print(" a+5 ",a+5)
print(" a-5 ", a-5)
print(" a*2 ",a*2)
print(" a/2 ",a/2)
print(" a//2  ", a/2)
print("  -a",-a)
print(" a**2 ",a**2)
print(" a%2 ",a%2)

a   = [0 1 2 3]
 a+5  [5 6 7 8]
 a-5  [-5 -4 -3 -2]
 a*2  [0 2 4 6]
 a/2  [0.  0.5 1.  1.5]
 a//2   [0.  0.5 1.  1.5]
  -a [ 0 -1 -2 -3]
 a**2  [0 1 4 9]
 a%2  [0 1 0 1]


In [8]:
a+a

array([0, 2, 4, 6])

In [9]:
a*a

array([0, 1, 4, 9])

In [ ]:
# SUMAR RESTAR con UFUNCTS
# np.add
# np.substract
# no,multiply

In [10]:
a=np.arange(4)
b=np.arange(1,5)

In [12]:
display(np.exp(a))            #exponencial
display(np.log(b))            #Logaritmo
display(np.sqrt(a))           #Raiz Cuadrada
display(np.greater(a,b))      # Superior o igual Punto a punto

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

array([0.        , 0.69314718, 1.09861229, 1.38629436])

array([0.        , 1.        , 1.41421356, 1.73205081])

array([False, False, False, False])

In [13]:
c=np.arange(10)

display(np.mean(a))
display(np.median(a))

np.percentile(a,40)


1.5

1.5

1.2000000000000002

In [14]:
np.random.random(10)

array([0.8430823 , 0.0814609 , 0.41983861, 0.63851406, 0.45025176,
       0.7417766 , 0.03210967, 0.62827642, 0.25603948, 0.82478287])