In [8]:
import numpy as np

In [9]:
a1= np.array([1,2,3])
a2=np.arange(10)


a3=np.zeros((2,3))

a4=np.ones((2,3))

a5=np.linspace(0,1,10)

In [10]:
display(a1)

array([1, 2, 3])

In [11]:
a3.shape

(2, 3)

In [13]:
a1D=np.array([1,2,3])
a2D=np.array([[1,2,3]])
display(a1D.shape)
display(a2D.shape)

(3,)

(1, 3)

In [14]:
np.array_equal(a1D,a2D)

False

In [17]:
new_dims=(1,a1D.shape[0])
a=a1D.reshape(new_dims)
a

array([[1, 2, 3]])

In [18]:
np.array_equal(a,a2D)

True

In [19]:
a=np.array([[1,0,3],[4,3,5],[6,10,-1]])
a

array([[ 1,  0,  3],
       [ 4,  3,  5],
       [ 6, 10, -1]])

In [22]:
a[2,1]

10

In [23]:
a=np.arange(10)
b=np.eye(3)
display(a);display(b)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [24]:
a[:5]

array([0, 1, 2, 3, 4])

In [25]:
b

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
b[0:3,1]

array([0., 1., 0.])

In [28]:
b[2,0:3]

array([0., 0., 1.])

In [29]:
b[2:]

array([[0., 0., 1.]])

In [30]:
b[:,:]

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])